services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWD?MUST BE SET}
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  brc20-prog:
    build: ./brc20-prog
    env_file:
      - .env
    environment:
      - BRC20_PROG_RPC_SERVER_URL=0.0.0.0:18545
      - BRC20_PROG_BALANCE_SERVER_URL=http://brc20-index:18546
      - BITCOIN_RPC_URL=http://brc20-index:18547
      - BRC20_PROG_DB_PATH=/var/lib/brc20-prog/data
    restart: unless-stopped
    # Expose JSON-RPC:
    ports:
      - "18545:18545"
    volumes:
      - brc20_prog_data:/var/lib/brc20-prog/data

  brc20-index:
    build: ./brc20-index
    depends_on:
      - db
      - brc20-prog
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWD=${DB_PASSWD}
      - DB_DATABASE=postgres
      - DB_SSL=false
      - BRC20_PROG_RPC_URL=http://brc20-prog:18545
      - BRC20_PROG_BALANCE_SERVER_ADDR=0.0.0.0:18546
      - BITCOIN_RPC_PROXY_SERVER_ADDR=0.0.0.0:18547
    restart: unless-stopped

  brc20-api:
    build: ./brc20-api
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PASSWD=${DB_PASSWD}
      - DB_SSL=false
      - API_HOST=0.0.0.0
      - API_PORT=${API_PORT:-8000}
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"

volumes:
  db_data:
  brc20_prog_data: